CREATE TABLE IF NOT EXISTS note(
    id INTEGER PRIMARY KEY AUTOINCREMENT
    title TEXT NOT NULL,
    created  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished DATETIME NOT NULL,
    status TEXT NOT NULL
);